name: Arch Linux Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on Arch Linux
    runs-on: ubuntu-latest
    container: 
      image: archlinux:base-devel

    steps:
    - name: Install Git and CMake
      run: |
        pacman -Sy --noconfirm
        pacman -S --noconfirm git cmake

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Node.js
      run: pacman -S --noconfirm nodejs npm

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test